listeners:
- query_port: 25575
  motd: '&l&bAystralia Network &f| &aSurvival &f| &9Skyblock &f| &7Prison &f| &eCreative'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 139.99.208.69:25565
  max_players: 1000
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: cb5a3ba7-6bb2-4fab-a9bc-3fa32b297736
player_limit: -1
ip_forward: true
groups:
  Al_Shebab:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  Hub:
    motd: '&b&lAystralia Network &f&l| &f&lHub'
    address: localhost:25560
    restricted: false
  Survival:
    motd: '&b&lAystralia Network &f&l| &a&lSurvival'
    address: localhost:25561
    restricted: false
  Skyblock:
    motd: '&b&lAystralia Network &f&l| &9&lSkyblock'
    address: localhost:25562
    restricted: false
  Creative:
    motd: '&b&lAystralia Network &f&l| &e&lCreative'
    address: localhost:25563
    restricted: false
  Prison:
    motd: '&b&lAystralia Network &f&l| &7&lPrison'
    address: localhost:25564
    restricted: false
